version: '3'
services:
  valkey:
    image: 'valkey/valkey:7.2'
    restart: unless-stopped
    expose:
      - '6379'
    volumes:
      - 'valkey-data:/data'

  postgres:
    image: 'postgres:16.2-alpine'
    restart: unless-stopped
    expose:
      - '5432'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  rabbitmq:
    image: 'rabbitmq:3.13-management'
    hostname: rabbitmq
    restart: unless-stopped
    expose:
      - '5672'
    environment:
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}'
    volumes:
      - 'rabbitmq-data:/var/lib/rabbitmq'
    healthcheck:
      test:
        - CMD-SHELL
        - 'rabbitmq-diagnostics check_port_connectivity || exit 1'
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  webhook_handler:
    image: 'ghcr.io/bsquidwrd/twitcheventsubhandler-receiver:main'
    restart: unless-stopped
    expose:
      - '${PORT}'
    environment:
      - 'PORT=${PORT}'
      - 'EVENTSUBSECRET=${EVENTSUBSECRET}'
      - 'CLIENTID=${CLIENTID}'
      - 'CLIENTSECRET=${CLIENTSECRET}'
      - 'CACHE_URL=${CACHE_URL}'
      - 'DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASS}@postgres:5432/${POSTGRES_USER}'
      - 'QUEUE_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/'
    depends_on:
      valkey:
        condition: service_started
        restart: true
      postgres:
        condition: service_started
        restart: true
      rabbitmq:
        condition: service_healthy
        restart: true

  discord_notifier:
    image: 'ghcr.io/bsquidwrd/twitcheventsubhandler-discordnotifier:main'
    restart: unless-stopped
    expose:
      - '${PORT}'
    environment:
      - 'PORT=${PORT}'
      - 'CACHE_URL=${CACHE_URL}'
      - 'DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASS}@postgres:5432/${POSTGRES_USER}'
      - 'QUEUE_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/'
    depends_on:
      valkey:
        condition: service_started
        restart: true
      postgres:
        condition: service_started
        restart: true
      rabbitmq:
        condition: service_healthy
        restart: true

volumes:
  valkey-data:
    driver: local
  db-data:
    driver: local
  rabbitmq-data:
    driver: local
