---
version: "3"

services:
  valkey:
    image: valkey/valkey:7.2
    restart: always
    volumes:
      - valkey-data:/data
    networks:
      - backend

  postgres:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_port_connectivity || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  webhook_handler:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      valkey:
        condition: service_started
        restart: true
      postgres:
        condition: service_started
        restart: true
      rabbitmq:
        condition: service_healthy
        restart: true
    networks:
      - backend
      - frontend

volumes:
  valkey-data:
    driver: local
  db-data:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  backend:
  frontend:
    driver: bridge
