---
version: "3"

services:
  valkey:
    image: valkey/valkey:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data

  postgres:
    image: postgres:16.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  valkey-data:
    driver: local
  db-data:
    driver: local
  rabbitmq-data:
    driver: local
